# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cdyo0amske5RXv0JiDDxKdQqkKpvBGU-
"""

!pip install -q transformers accelerate torch gradio huggingface_hub

# Medical AI Assistant with IBM Granite 3.3 2B Instruct
# Single-cell implementation for Google Colab

# Install required packages
!pip install -q transformers accelerate torch gradio huggingface_hub

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import json
from typing import List, Dict
import re

# Initialize the model and tokenizer
print("Loading IBM Granite 3.3 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print("Model loaded successfully!")

# Drug interaction database (simplified for demonstration)
DRUG_INTERACTIONS = {
    "aspirin": ["warfarin", "ibuprofen", "naproxen", "clopidogrel"],
    "warfarin": ["aspirin", "ibuprofen", "naproxen", "vitamin k"],
    "metformin": ["alcohol", "contrast dye"],
    "lisinopril": ["potassium supplements", "spironolactone"],
    "simvastatin": ["grapefruit juice", "clarithromycin", "itraconazole"],
    "ibuprofen": ["aspirin", "warfarin", "lisinopril"],
    "amoxicillin": ["methotrexate", "warfarin"],
    "methotrexate": ["amoxicillin", "nsaids", "proton pump inhibitors"]
}

# Age-specific dosage guidelines (simplified)
DOSAGE_GUIDELINES = {
    "aspirin": {
        "infant": "Not recommended under 12 years",
        "child": "10-15 mg/kg every 4-6 hours (max 4g/day)",
        "adult": "325-650 mg every 4-6 hours (max 4g/day)",
        "elderly": "Start with lower dose, 81-325 mg daily for prevention"
    },
    "ibuprofen": {
        "infant": "5-10 mg/kg every 6-8 hours (6 months+)",
        "child": "10 mg/kg every 6-8 hours (max 40 mg/kg/day)",
        "adult": "200-400 mg every 4-6 hours (max 3200 mg/day)",
        "elderly": "Start with lowest dose, monitor for GI effects"
    },
    "metformin": {
        "infant": "Not recommended",
        "child": "Start 500 mg twice daily, max 2000 mg/day (10+ years)",
        "adult": "Start 500 mg twice daily, max 2550 mg/day",
        "elderly": "Lower starting dose, monitor renal function"
    }
}

# Alternative medications database
ALTERNATIVES = {
    "aspirin": ["ibuprofen", "acetaminophen", "naproxen"],
    "ibuprofen": ["naproxen", "acetaminophen", "celecoxib"],
    "metformin": ["glipizide", "sitagliptin", "empagliflozin"],
    "lisinopril": ["losartan", "valsartan", "enalapril"],
    "simvastatin": ["atorvastatin", "rosuvastatin", "pravastatin"]
}

def generate_response(prompt: str, max_length: int = 512) -> str:
    """Generate response using IBM Granite model"""
    messages = [
        {"role": "system", "content": "You are a knowledgeable medical AI assistant. Provide accurate, helpful information about medications, dosages, and drug interactions. Always remind users to consult healthcare professionals."},
        {"role": "user", "content": prompt}
    ]

    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
    return response.strip()

def extract_drugs_from_text(text: str) -> List[str]:
    """Extract drug names from text using NLP"""
    text_lower = text.lower()
    found_drugs = []

    # Check against known drugs
    all_drugs = set(DRUG_INTERACTIONS.keys()) | set(DOSAGE_GUIDELINES.keys())
    for drug in all_drugs:
        if drug in text_lower:
            found_drugs.append(drug)

    return found_drugs

def check_drug_interactions(drugs: List[str]) -> str:
    """Check for drug interactions"""
    if len(drugs) < 2:
        return "⚠️ Please provide at least 2 drugs to check interactions.\n"

    interactions_found = []
    for i, drug1 in enumerate(drugs):
        drug1_lower = drug1.lower()
        if drug1_lower in DRUG_INTERACTIONS:
            for drug2 in drugs[i+1:]:
                drug2_lower = drug2.lower()
                if drug2_lower in DRUG_INTERACTIONS[drug1_lower]:
                    interactions_found.append(f"⚠️ INTERACTION: {drug1} ↔ {drug2}")

    if interactions_found:
        result = "🚨 **Drug Interactions Detected:**\n\n"
        result += "\n".join(interactions_found)
        result += "\n\n⚕️ Please consult your healthcare provider about these interactions."
    else:
        result = "✅ No known interactions detected between these medications.\n"
        result += "⚕️ Always consult your healthcare provider before combining medications."

    return result

def get_age_specific_dosage(drug: str, age_group: str) -> str:
    """Get age-specific dosage recommendations"""
    drug_lower = drug.lower()

    if drug_lower not in DOSAGE_GUIDELINES:
        # Use AI to generate dosage info
        prompt = f"Provide age-specific dosage recommendations for {drug} for {age_group} patients. Be specific and include safety warnings."
        ai_response = generate_response(prompt, max_length=300)
        return f"📋 **Dosage for {drug} ({age_group}):**\n\n{ai_response}\n\n⚕️ Always consult a healthcare professional for personalized dosing."

    dosage_info = DOSAGE_GUIDELINES[drug_lower]
    age_key = age_group.lower()

    if age_key in dosage_info:
        dosage = dosage_info[age_key]
    else:
        dosage = "Please specify age group: infant, child, adult, or elderly"

    result = f"📋 **Dosage for {drug} ({age_group}):**\n\n{dosage}\n\n"
    result += "⚕️ These are general guidelines. Always consult a healthcare professional for personalized dosing."

    return result

def get_alternative_medications(drug: str, reason: str = "") -> str:
    """Suggest alternative medications"""
    drug_lower = drug.lower()

    if drug_lower in ALTERNATIVES:
        alternatives = ALTERNATIVES[drug_lower]
        result = f"💊 **Alternative medications for {drug}:**\n\n"
        for alt in alternatives:
            result += f"• {alt.title()}\n"
    else:
        # Use AI to suggest alternatives
        prompt = f"Suggest 3-4 alternative medications for {drug}"
        if reason:
            prompt += f" considering the following reason: {reason}"
        prompt += ". Explain briefly why each alternative might be suitable."

        ai_response = generate_response(prompt, max_length=400)
        result = f"💊 **Alternative medications for {drug}:**\n\n{ai_response}\n"

    result += "\n⚕️ Discuss these alternatives with your healthcare provider before making any changes."
    return result

def extract_drug_information(query: str) -> str:
    """Extract and provide drug information using NLP"""
    drugs = extract_drugs_from_text(query)

    if not drugs:
        # Use AI to understand and respond to the query
        prompt = f"Extract medication information from this query and provide a helpful response: {query}"
        ai_response = generate_response(prompt, max_length=400)
        return f"🔍 **Drug Information Extraction:**\n\n{ai_response}"

    result = f"🔍 **Extracted Drugs:** {', '.join([d.title() for d in drugs])}\n\n"

    # Generate comprehensive information using AI
    prompt = f"Provide comprehensive information about these medications: {', '.join(drugs)}. Include uses, side effects, and precautions."
    ai_response = generate_response(prompt, max_length=500)
    result += ai_response

    return result

# Gradio Interface Functions
def interaction_checker(drug_list: str) -> str:
    """Interface function for drug interaction checking"""
    drugs = [d.strip() for d in drug_list.split(',') if d.strip()]
    return check_drug_interactions(drugs)

def dosage_recommender(drug: str, age_group: str) -> str:
    """Interface function for dosage recommendations"""
    if not drug.strip():
        return "⚠️ Please enter a drug name."
    return get_age_specific_dosage(drug, age_group)

def alternative_finder(drug: str, reason: str) -> str:
    """Interface function for alternative medications"""
    if not drug.strip():
        return "⚠️ Please enter a drug name."
    return get_alternative_medications(drug, reason)

def information_extractor(query: str) -> str:
    """Interface function for NLP-based information extraction"""
    if not query.strip():
        return "⚠️ Please enter a query."
    return extract_drug_information(query)

# Create Gradio Interface
with gr.Blocks(title="Medical AI Assistant", theme=gr.themes.Soft()) as app:
    gr.Markdown("""
    # 🏥 Medical AI Assistant with IBM Granite 3.3 2B

    ### Powered by IBM Granite 3.1 2B Instruct Model

    **⚠️ DISCLAIMER:** This tool is for informational purposes only. Always consult qualified healthcare professionals before making medical decisions.
    """)

    with gr.Tabs():
        # Tab 1: Drug Interaction Detection
        with gr.Tab("💊 Drug Interactions"):
            gr.Markdown("### Check for interactions between multiple drugs")
            interaction_input = gr.Textbox(
                label="Enter drugs (comma-separated)",
                placeholder="e.g., aspirin, warfarin, ibuprofen",
                lines=2
            )
            interaction_button = gr.Button("Check Interactions", variant="primary")
            interaction_output = gr.Markdown(label="Results")

            interaction_button.click(
                fn=interaction_checker,
                inputs=interaction_input,
                outputs=interaction_output
            )

            gr.Examples(
                examples=[
                    ["aspirin, warfarin"],
                    ["ibuprofen, lisinopril, aspirin"],
                    ["metformin, alcohol"]
                ],
                inputs=interaction_input
            )

        # Tab 2: Age-Specific Dosage
        with gr.Tab("📋 Dosage Recommendations"):
            gr.Markdown("### Get age-appropriate dosage recommendations")
            with gr.Row():
                dosage_drug = gr.Textbox(
                    label="Drug Name",
                    placeholder="e.g., aspirin",
                    scale=2
                )
                age_group = gr.Radio(
                    choices=["Infant", "Child", "Adult", "Elderly"],
                    label="Age Group",
                    value="Adult",
                    scale=1
                )
            dosage_button = gr.Button("Get Dosage", variant="primary")
            dosage_output = gr.Markdown(label="Dosage Information")

            dosage_button.click(
                fn=dosage_recommender,
                inputs=[dosage_drug, age_group],
                outputs=dosage_output
            )

            gr.Examples(
                examples=[
                    ["aspirin", "Adult"],
                    ["ibuprofen", "Child"],
                    ["metformin", "Elderly"]
                ],
                inputs=[dosage_drug, age_group]
            )

        # Tab 3: Alternative Medications
        with gr.Tab("🔄 Alternative Medications"):
            gr.Markdown("### Find alternative medication options")
            alt_drug = gr.Textbox(
                label="Current Medication",
                placeholder="e.g., aspirin",
                lines=1
            )
            alt_reason = gr.Textbox(
                label="Reason for Alternative (optional)",
                placeholder="e.g., allergic reaction, side effects, cost concerns",
                lines=2
            )
            alt_button = gr.Button("Find Alternatives", variant="primary")
            alt_output = gr.Markdown(label="Alternative Options")

            alt_button.click(
                fn=alternative_finder,
                inputs=[alt_drug, alt_reason],
                outputs=alt_output
            )

            gr.Examples(
                examples=[
                    ["aspirin", "stomach irritation"],
                    ["simvastatin", "muscle pain"],
                    ["lisinopril", "persistent cough"]
                ],
                inputs=[alt_drug, alt_reason]
            )

        # Tab 4: NLP Drug Information
        with gr.Tab("🔍 Drug Information Extraction"):
            gr.Markdown("### Extract drug information from natural language queries")
            nlp_query = gr.Textbox(
                label="Your Query",
                placeholder="e.g., I'm taking aspirin and ibuprofen for pain. What should I know?",
                lines=3
            )
            nlp_button = gr.Button("Extract Information", variant="primary")
            nlp_output = gr.Markdown(label="Extracted Information")

            nlp_button.click(
                fn=information_extractor,
                inputs=nlp_query,
                outputs=nlp_output
            )

            gr.Examples(
                examples=[
                    ["What are the side effects of metformin?"],
                    ["I'm taking aspirin and warfarin together, is this safe?"],
                    ["Tell me about ibuprofen dosage for children"]
                ],
                inputs=nlp_query
            )

    gr.Markdown("""
    ---
    ### 📌 Features:
    - **Drug Interaction Detection**: Identify potential interactions between medications
    - **Age-Specific Dosage**: Get appropriate dosing for different age groups
    - **Alternative Medications**: Find suitable alternatives for various reasons
    - **NLP Information Extraction**: Natural language understanding of drug queries

    ### ⚕️ Important Notes:
    - This is an AI-powered educational tool
    - Always verify information with healthcare professionals
    - Never stop or change medications without consulting your doctor
    - In case of emergency, contact local emergency services
    """)

# Launch the application
print("\n" + "="*50)
print("🚀 Launching Medical AI Assistant...")
print("="*50 + "\n")

app.launch(share=True, debug=True)